# Generated by Django 5.2.17 on 2026-09-30 15:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(max_length=40)),
                ('input_name', models.CharField(max_length=250)),
                ('fingerprint', models.CharField(max_length=64)),
                ('created', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('unchanged', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=1000, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])])),
                ('region', models.CharField(max_length=40)),
                ('access_method', models.CharField(choices=[('manual', '人工审核'), ('feed', '正式 Feed/API')], default='manual', max_length=20)),
                ('terms_url', models.URLField(blank=True, max_length=1000, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])])),
                ('robots_url', models.URLField(blank=True, max_length=1000, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])])),
                ('policy_note', models.TextField(blank=True)),
                ('automation_allowed', models.BooleanField(default=False)),
                ('policy_checked_at', models.DateTimeField(blank=True, null=True)),
                ('rate_seconds', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(3600)])),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('position', '博士招聘岗位'), ('program_round', '博士项目申请轮次'), ('scholarship', '奖学金 / 资助'), ('postdoc', '博士后'), ('visiting', '访问学者')], max_length=20)),
                ('identity', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=350)),
                ('title_zh', models.CharField(max_length=350)),
                ('country', models.CharField(max_length=60)),
                ('region', models.CharField(max_length=40)),
                ('discipline', models.CharField(max_length=80)),
                ('url', models.URLField(max_length=1000, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])])),
                ('application_url', models.URLField(blank=True, max_length=1000, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])])),
                ('round_key', models.CharField(blank=True, max_length=150)),
                ('round_label', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('open', '开放申请'), ('upcoming', '未来轮次'), ('unknown', '状态待核验'), ('closed', '已关闭')], default='unknown', max_length=20)),
                ('status_note', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('pending', '待审核'), ('verified', '已审核')], default='pending', max_length=20)),
                ('is_test', models.BooleanField(default=False)),
                ('summary_zh', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('language_requirements', models.TextField(blank=True)),
                ('employment_type', models.CharField(choices=[('unknown', '未知 / 原文未说明'), ('employee', '雇佣'), ('student', '学生身份'), ('scholarship', '奖学金身份')], default='unknown', max_length=20)),
                ('funding_status', models.CharField(choices=[('unknown', '资助待核验'), ('funded', '有资助'), ('partial', '部分资助'), ('self_funded', '自费')], default='unknown', max_length=20)),
                ('funding_source', models.TextField(blank=True)),
                ('tuition_waiver', models.TextField(blank=True)),
                ('work_fraction', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('payment_schedule', models.TextField(blank=True)),
                ('translation_method', models.CharField(default='人工审核式中文整理；模型 API 未配置', max_length=60)),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_funding', models.ManyToManyField(blank=True, limit_choices_to={'type': 'scholarship'}, related_name='funded_opportunities', to='opportunities.opportunity')),
            ],
            options={
                'ordering': ['-verified_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FinancialFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('salary', '个人薪酬'), ('stipend', '个人津贴'), ('tuition_waiver', '学费减免'), ('tuition_fee', '学费'), ('application_fee', '申请费'), ('total_grant', '资助总额'), ('other', '其他费用 / 资助')], max_length=30)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(blank=True, max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', '使用 ISO 三字母币种')])),
                ('pay_period', models.CharField(choices=[('month', '月'), ('year', '年'), ('week', '周'), ('total', '总计'), ('once', '一次性'), ('unknown', '周期未说明')], default='unknown', max_length=20)),
                ('tax_basis', models.CharField(choices=[('gross', '税前'), ('net', '税后'), ('unknown', '税口径未说明')], default='unknown', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='opportunities.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('url', models.URLField(max_length=1000, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])])),
                ('verified_at', models.DateTimeField()),
                ('method', models.CharField(default='manual_review', max_length=30)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='opportunities.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('application', '申请截止'), ('funding', '资助截止'), ('consent', '导师同意截止'), ('document', '材料截止'), ('other', '其他')], default='application', max_length=30)),
                ('label', models.CharField(max_length=150)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=80)),
                ('original', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('verified', '已核验'), ('unknown', '待核验')], default='unknown', max_length=20)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='opportunities.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('university', '大学 / 科研机构'), ('lab', '课题组')], default='university', max_length=20)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('url', models.URLField(blank=True, max_length=1000, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])])),
                ('note', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='opportunities.organization')),
            ],
        ),
        migrations.AddField(
            model_name='opportunity',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opportunities.organization'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=1000, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])])),
                ('evidence', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opportunities.organization')),
            ],
        ),
        migrations.AddField(
            model_name='opportunity',
            name='mentors',
            field=models.ManyToManyField(blank=True, to='opportunities.person'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField(max_length=1000, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])])),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opportunities.organization')),
                ('mentors', models.ManyToManyField(blank=True, to='opportunities.person')),
            ],
        ),
        migrations.AddField(
            model_name='opportunity',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='opportunities.program'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opportunities.source'),
        ),
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.BooleanField(default=False)),
                ('stage', models.CharField(choices=[('none', '尚未开始'), ('preparing', '准备材料'), ('submitted', '已提交'), ('interview', '面试中'), ('offer', '获得录取'), ('rejected', '未录取'), ('withdrawn', '已撤回')], default='none', max_length=20)),
                ('note', models.TextField(blank=True, max_length=3000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_person_in_org'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'program_round')), fields=('program', 'round_key'), name='unique_program_round'),
        ),
        migrations.AddConstraint(
            model_name='userrecord',
            constraint=models.UniqueConstraint(fields=('user', 'opportunity'), name='unique_user_opportunity'),
        ),
    ]
