# Generated by Django 5.2.17 on 2026-09-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='kind',
            field=models.CharField(choices=[('application', '申请截止'), ('funding', '资助截止'), ('consent', '导师同意截止'), ('opening', '申请开放'), ('document', '材料截止'), ('other', '其他')], default='application', max_length=30),
        ),
    ]
