# Generated by Django 5.2.17 on 2026-09-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_alter_deadline_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='identity',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
