# Generated by Django 5.2.17 on 2026-09-30 17:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_alter_opportunity_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('base', models.CharField(default='EUR', max_length=3)),
                ('rates', models.JSONField()),
                ('url', models.URLField(max_length=1000, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])])),
                ('version', models.CharField(max_length=64, unique=True)),
                ('fetched_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='deadline',
            name='effect',
            field=models.CharField(choices=[('hard_close', '最终硬截止'), ('priority', '优先 / 充分考虑'), ('prerequisite', '前置步骤'), ('opening', '开放起日'), ('rolling', '滚动受理'), ('unknown', '性质待核验')], default='hard_close', max_length=20),
        ),
        migrations.AddField(
            model_name='deadline',
            name='precision',
            field=models.CharField(choices=[('date', '日期精度'), ('time', '时刻精度'), ('unknown', '精度待核验')], default='date', max_length=20),
        ),
        migrations.AddField(
            model_name='financialfact',
            name='applicable_year',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='financialfact',
            name='comparability_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialfact',
            name='condition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='financialfact',
            name='conditional_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='financialfact',
            name='currency_evidence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='financialfact',
            name='payments_per_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialfact',
            name='verification_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='financialfact',
            name='work_basis',
            field=models.CharField(choices=[('actual', '实际已折算工时'), ('full_time', '全职基准'), ('not_applicable', '津贴非雇佣工时'), ('unknown', '工时口径未知')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='deadline_mode',
            field=models.CharField(choices=[('fixed', '固定截止'), ('rolling', '全年 / 滚动受理'), ('not_applicable', '不适用'), ('unknown', '截止待核验')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='official_id',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='pending_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='review_method',
            field=models.CharField(default='codex_assisted_review', max_length=40),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='source_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='translated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='translation_status',
            field=models.CharField(choices=[('ready', '中文已整理'), ('stale', '中文及判断待更新'), ('pending', '中文待审核')], default='ready', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='external_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='person',
            name='external_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='source',
            name='adapter',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='source',
            name='review_period_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='source',
            name='scope',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='source',
            name='url_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='completed_steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='type',
            field=models.CharField(choices=[('position', '博士招聘岗位'), ('program_round', '博士项目申请轮次'), ('scholarship', '奖学金 / 资助'), ('postdoc', '博士后'), ('visiting', '正式访问机会'), ('research_funding', '机构科研资助')], max_length=20),
        ),
        migrations.CreateModel(
            name='LocalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SourceAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=False)),
                ('scope', models.JSONField(default=dict)),
                ('policy_url', models.URLField(max_length=1000, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])])),
                ('evidence', models.TextField()),
                ('method', models.CharField(default='documented_policy_review', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='opportunities.source')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(max_length=1000, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])])),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('method', models.CharField(default='live_api', max_length=40)),
                ('status', models.CharField(default='started', max_length=30)),
                ('parsed', models.PositiveIntegerField(default=0)),
                ('proposed', models.PositiveIntegerField(default=0)),
                ('unchanged', models.PositiveIntegerField(default=0)),
                ('applied', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opportunities.source')),
            ],
        ),
        migrations.CreateModel(
            name='VisitPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=180, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=1000, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])])),
                ('identity_types', models.JSONField(default=list)),
                ('details', models.JSONField(default=dict)),
                ('evidence', models.JSONField(default=list)),
                ('verified_at', models.DateTimeField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opportunities.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=180, unique=True)),
                ('region', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=60)),
                ('themes', models.JSONField(default=list)),
                ('url', models.URLField(max_length=1000, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])])),
                ('receiving_status', models.CharField(choices=[('open', '明确开放招募'), ('institutional_path', '制度存在 · 名额未知'), ('external_funding', '明确欢迎特定外部资助'), ('historical', '历史接收证据'), ('unknown', '接收未确认'), ('closed', '明确关闭')], default='unknown', max_length=30)),
                ('eligibility_status', models.CharField(default='unknown', max_length=20)),
                ('funding_type', models.CharField(default='unknown', max_length=20)),
                ('match_category', models.CharField(default='unknown', max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('evidence', models.JSONField(default=list)),
                ('verified_at', models.DateTimeField()),
                ('pending_change', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_targets', to='opportunities.organization')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opportunities.organization')),
                ('mentors', models.ManyToManyField(to='opportunities.person')),
                ('paths', models.ManyToManyField(to='opportunities.visitpath')),
            ],
        ),
        migrations.CreateModel(
            name='EntityRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=30)),
                ('entity_key', models.CharField(max_length=220)),
                ('sequence', models.PositiveIntegerField()),
                ('old', models.JSONField(default=dict)),
                ('new', models.JSONField(default=dict)),
                ('source_record_id', models.CharField(blank=True, max_length=220)),
                ('source_revision', models.CharField(blank=True, max_length=100)),
                ('observed_at', models.DateTimeField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('application_version', models.CharField(default='G2-20261001', max_length=40)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='opportunities.source')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'entity_key', 'sequence'), name='unique_entity_revision')],
            },
        ),
        migrations.CreateModel(
            name='FundingRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('independent', '独立申请'), ('same_application', '同一申请内选择'), ('automatic_consideration', '自动考虑'), ('nomination', '提名申请'), ('unknown', '申请关系待核验')], default='unknown', max_length=30)),
                ('conditions', models.TextField(blank=True)),
                ('evidence', models.JSONField(default=list)),
                ('exclusive_group', models.CharField(blank=True, max_length=100)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='award_relations', to='opportunities.opportunity')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funding_relations', to='opportunities.opportunity')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('opportunity', 'award'), name='unique_funding_relation')],
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('path', models.CharField(default='/targets/', max_length=100)),
                ('query', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_user_filter')],
            },
        ),
        migrations.CreateModel(
            name='SourceAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=220)),
                ('original_url', models.URLField(blank=True, max_length=1000, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])])),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='opportunities.opportunity')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='opportunities.organization')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='opportunities.person')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opportunities.source')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='opportunities.researchtarget')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'record_id'), name='unique_source_record')],
            },
        ),
        migrations.CreateModel(
            name='TargetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, max_length=3000)),
                ('stage', models.CharField(default='researching', max_length=30)),
                ('completed_steps', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opportunities.researchtarget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'target'), name='unique_user_target')],
            },
        ),
        migrations.CreateModel(
            name='UpdateProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=220)),
                ('kind', models.CharField(max_length=40)),
                ('payload', models.JSONField()),
                ('diff', models.JSONField(default=dict)),
                ('fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', '待审核'), ('applied', '已应用'), ('conflict', '冲突'), ('rejected', '已拒绝')], default='pending', max_length=30)),
                ('observed_at', models.DateTimeField()),
                ('source_revision', models.CharField(blank=True, max_length=100)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opportunities.source')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='opportunities.updaterun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'record_id', 'fingerprint'), name='unique_source_payload')],
            },
        ),
    ]
