# Generated by Django 5.2.17 on 2026-09-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_g1_public_baseline'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='updateproposal',
            name='unique_source_payload',
        ),
        migrations.AlterField(
            model_name='financialfact',
            name='tax_basis',
            field=models.CharField(choices=[('gross', '税前'), ('net', '税后'), ('exempt', '明确免税'), ('unknown', '税口径未说明')], default='unknown', max_length=20),
        ),
    ]
