# Generated by Django 5.2.17 on 2026-09-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_remove_updateproposal_unique_source_payload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialfact',
            name='applicable_year',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
