# Generated by Django 5.2.17 on 2026-09-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0007_alter_financialfact_applicable_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingrelation',
            name='evidence',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
