# Generated by Django 5.2.17 on 2026-09-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0008_alter_fundingrelation_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='retry_after_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
