# Generated by Django 5.2.17 on 2026-10-01 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0009_source_retry_after_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='requirement_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='deadline',
            name='step_id',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='sourcealias',
            name='path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='opportunities.visitpath'),
        ),
        migrations.AddField(
            model_name='updateproposal',
            name='base_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='updateproposal',
            name='revision_type',
            field=models.CharField(default='opaque', max_length=20),
        ),
        migrations.CreateModel(
            name='DecisionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('comparison', '目标比较'), ('budget', '预算方案'), ('contact', '联系准备')], max_length=20)),
                ('inputs', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('versions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='opportunities.visitpath')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='opportunities.researchtarget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
