# Generated by Django 5.2.17 on 2026-10-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0011_stable_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcealias',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
