# Generated by Django 5.2.17 on 2026-10-01 12:38

from django.db import migrations, models

def preserve_public_history(apps, schema_editor):
    apps.get_model('opportunities','Opportunity').objects.filter(review_status='verified',is_test=False).update(is_published=True)
    apps.get_model('opportunities','ResearchTarget').objects.all().update(is_published=True)
    apps.get_model('opportunities','VisitPath').objects.all().update(is_published=True)


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0012_sourcealias_checked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='researchtarget',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitpath',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(preserve_public_history, migrations.RunPython.noop),
    ]
