# Generated by Django 5.2.17 on 2026-10-01 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0013_opportunity_is_published_researchtarget_is_published_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PathSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_support', models.BooleanField(blank=True, null=True)),
                ('agreement_ready', models.BooleanField(blank=True, null=True)),
                ('evidence_note', models.TextField(blank=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opportunities.visitpath')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opportunities.researchtarget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'target', 'path'), name='unique_user_target_path_support')],
            },
        ),
    ]
