# Generated by Django 5.2.17 on 2026-10-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0014_pathsupport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='effect',
            field=models.CharField(choices=[('hard_close', '最终硬截止'), ('priority', '优先 / 充分考虑'), ('prerequisite', '前置步骤'), ('opening', '开放起日'), ('rolling', '滚动受理'), ('informational', '信息事件 / 程序'), ('unknown', '性质待核验')], default='hard_close', max_length=20),
        ),
    ]
