# Generated by Django 5.2.17 on 2026-10-01 17:18

from django.db import migrations, models
from django.utils import timezone


def retain_public_headers(apps,schema_editor):
    Decision=apps.get_model('opportunities','DecisionRecord')
    Target=apps.get_model('opportunities','ResearchTarget')
    for record in Decision.objects.all():
        choices=record.inputs.get('choices',[]) if record.kind=='comparison' else [{'target':record.target_id,'path':record.path_id}]
        headers=[]
        for choice in choices:
            target=Target.objects.filter(pk=choice.get('target'),is_published=True).first()
            path=target.paths.filter(pk=choice.get('path'),is_published=True).first() if target else None
            if path: headers.append({'target':target.pk,'path':path.pk,'name':path.name,'url':path.url,'published_checked_at':timezone.now().isoformat(),'scope':'G4 migration public-header check, not a new fact verification'})
        Decision.objects.filter(pk=record.pk).update(public_paths=headers)


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0015_alter_deadline_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionrecord',
            name='public_paths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(retain_public_headers,migrations.RunPython.noop),
    ]
