# Generated by Django 5.2.17 on 2026-10-02 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0016_decisionrecord_public_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialfact',
            name='applicability_basis',
            field=models.CharField(choices=[('year', '官方年度'), ('advertisement', '本公告现行报价')], default='year', max_length=20),
        ),
        migrations.AddField(
            model_name='financialfact',
            name='applicability_scope',
            field=models.URLField(blank=True, max_length=1000, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])]),
        ),
        migrations.AddField(
            model_name='financialfact',
            name='scope_observed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
