# Generated by Django 5.2.17 on 2026-10-02 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0017_financialfact_applicability_basis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=180, unique=True)),
                ('official_name', models.CharField(max_length=250)),
                ('qs_rank', models.PositiveIntegerField()),
                ('ranking_year', models.PositiveIntegerField(default=2027)),
                ('country', models.CharField(max_length=80)),
                ('relevant_departments', models.JSONField(default=list)),
                ('entries', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('checked_relevant_opportunities', '发现相关入口或机会'), ('checked_none', '已检查范围内未发现'), ('blocked', '访问受限'), ('pending', '尚待检查')], default='pending', max_length=40)),
                ('evidence', models.JSONField(default=list)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['qs_rank', 'official_name'],
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='curation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='researchtarget',
            name='curation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='updateproposal',
            name='applied_entity_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='organization',
            name='coverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='opportunities.coverageinstitution'),
        ),
    ]
