# Generated by Django 5.2.17 on 2026-10-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0018_coverageinstitution_opportunity_curation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='type',
            field=models.CharField(choices=[('position', '博士招聘岗位'), ('program_round', '博士项目申请轮次'), ('scholarship', '奖学金 / 资助'), ('postdoc', '博士后'), ('visiting', '正式访问机会'), ('research_funding', '机构科研资助'), ('doctoral_notice', '实验室博士招募（需先录取）')], max_length=20),
        ),
    ]
