# Generated by Django 5.2.17 on 2026-10-02 19:36

from django.db import migrations, models


def retain_old_states(apps, schema_editor):
    Registry=apps.get_model('opportunities','CoverageInstitution')
    mapping={'checked_relevant_opportunities':'relevant_opportunity_found',
             'checked_none':'bounded_entry_checked_no_extracted_opportunity','pending':'pending_review'}
    for row in Registry.objects.filter(status__in=mapping):
        row.review={**row.review,'legacy_status':row.status,'legacy_checked_at':row.last_checked_at.isoformat() if row.last_checked_at else None,
                    'migration_note':'原状态保留；未抽取不等于确认没有机会，等待有界反向复核'}
        row.status=mapping[row.status];row.save(update_fields=['review','status'])


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0019_alter_opportunity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverageinstitution',
            name='review',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='coverageinstitution',
            name='status',
            field=models.CharField(choices=[('relevant_opportunity_found', '已发现相关机会'), ('bounded_entry_checked_no_extracted_opportunity', '有限入口已查 · 尚未抽取机会'), ('verified_none_in_declared_scope', '声明范围反查后未发现'), ('blocked', '来源受限'), ('pending_review', '待复核')], default='pending_review', max_length=64),
        ),
        migrations.RunPython(retain_old_states,migrations.RunPython.noop),
    ]
