# Generated by Django 5.2.17 on 2026-10-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0020_coverage_review_semantics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='type',
            field=models.CharField(choices=[('position', '博士招聘岗位'), ('program_round', '博士项目申请轮次'), ('scholarship', '奖学金 / 资助'), ('postdoc', '博士后'), ('visiting', '正式访问机会'), ('research_funding', '机构科研资助'), ('doctoral_notice', '实验室博士招募意向（须核录取与轮次）'), ('doctoral_program', '博士项目路径（轮次未确认）'), ('visiting_route', '公开访问路径（名额未确认）')], max_length=20),
        ),
    ]
