# Generated by Django 5.2.17 on 2026-10-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0021_distinguish_program_and_visit_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverageinstitution',
            name='status',
            field=models.CharField(choices=[('relevant_opportunity_found', 'QS审计入口已发现'), ('bounded_entry_checked_no_extracted_opportunity', 'QS审计有限入口 · 尚未抽取'), ('verified_none_in_declared_scope', '声明范围反查后未发现'), ('blocked', 'QS审计入口受限'), ('pending_review', 'QS审计待复核')], default='pending_review', max_length=64, verbose_name='QS审计入口状态'),
        ),
    ]
