# Generated by Django 5.2.17 on 2026-10-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0024_opportunity_identity_discriminator'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='identity_fit',
            field=models.CharField(choices=[('directly_applicable', '当前博士身份适用'), ('potentially_applicable', '可能适用 · 须核身份'), ('future_only', '后续阶段 / 新学位申请'), ('not_applicable', '当前身份不适用'), ('unknown', '身份适配未知')], db_index=True, default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='researchtarget',
            name='actionability',
            field=models.CharField(choices=[('contact_candidate', '精选可联系导师'), ('research_watchlist', '研究观察名单'), ('reference_only', '参考科研人员')], db_index=True, default='research_watchlist', max_length=30),
        ),
        migrations.AddField(
            model_name='researchtarget',
            name='classification_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='researchtarget',
            name='contact_receiving_status',
            field=models.CharField(choices=[('explicitly_open', '明确开放接收'), ('inquiries_welcome', '明确欢迎咨询'), ('current_program_open', '相关项目当前开放'), ('unknown_contact_to_confirm', '当前接收待联系确认'), ('not_receiving', '明确不接收'), ('not_applicable', '不适用')], default='unknown_contact_to_confirm', max_length=35),
        ),
        migrations.AddField(
            model_name='researchtarget',
            name='host_capability',
            field=models.CharField(choices=[('confirmed_by_official_policy_or_profile', '正式指导 / Host能力有据'), ('plausible_but_unverified', '具备可能性 · 尚未确认'), ('restricted', 'Host能力受限'), ('not_applicable', '不适用'), ('unknown', 'Host能力未知')], default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='researchtarget',
            name='role_class',
            field=models.CharField(choices=[('independent_pi', '独立 PI'), ('faculty_supervisor', '教师 / 研究指导者'), ('group_leader', '课题组负责人'), ('independent_fellow', '独立研究会士'), ('research_staff', '研究人员'), ('postdoc', '博士后'), ('emeritus_retired', '荣休 / 退休'), ('former', '曾任'), ('unknown', '角色尚未确认')], db_index=True, default='unknown', max_length=30),
        ),
    ]
